{{ if .Values.developer -}}
{{ if .Values.developer.enabled -}}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-access-role-namespace
  namespace: dbt-cloud
  labels:
    {{- include "cluster_rbac.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/attach
      - pods/exec
      - pods/log
      - pods/portforward
      - pods/proxy
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-access-binding
  namespace: dbt-cloud
  labels:
    {{- include "cluster_rbac.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dev-access-role-namespace
subjects:
  - kind: Group
    name: devs

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-access-cluster-role
  labels:
    {{- include "cluster_rbac.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dev-access-cluster-binding
  labels:
    {{- include "cluster_rbac.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dev-access-cluster-role
subjects:
  - kind: Group
    name: devs
{{- end }}
{{- end }}
