kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: poweruser-access-role-namespace
  namespace: {{ .Values.rbacNamespace }}
  labels:
    {{- include "cluster_rbac.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/attach
      - pods/exec
      - pods/log
      - pods/portforward
      - pods/proxy
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: poweruser-access-binding
  namespace: {{ .Values.rbacNamespace }}
  labels:
    {{- include "cluster_rbac.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: poweruser-access-role-namespace
subjects:
  - kind: Group
    name: powerusers
